export const DEFAULT_SCENE_DURATION_SECONDS = 10;
export const DEFAULT_IMAGES_PER_SCENE = 4;
export const DEFAULT_IMAGE_BATCH_SIZE = 4;
export const AI_CREATOR_MAX_IMAGES_PER_SCENE = 12;
export const IMAGE_API_MAX_IMAGES_PER_REQUEST = 4;
