INSERT INTO "AiModel" (
    "id",
    "key",
    "provider",
    "providerModelId",
    "type",
    "displayName",
    "qualityTier",
    "supportedAspectRatios",
    "supportedResolutions",
    "supportsStartFrame",
    "supportsEndFrame",
    "supportsSeed",
    "pricePerSecondByResolution",
    "minDurationSeconds",
    "maxDurationSeconds",
    "defaultDurationSeconds",
    "active",
    "updatedAt"
) VALUES (
    'aimodel_kling_v3_pro_image_to_video',
    'kling-v3-pro-image-to-video',
    'fal',
    'fal-ai/kling-video/v3/pro/image-to-video',
    'image-to-video',
    'Kling V3 Pro Image To Video',
    'premium',
    ARRAY['auto'],
    ARRAY['pro'],
    true,
    true,
    false,
    '{"pro":12}'::jsonb,
    3,
    15,
    5,
    true,
    CURRENT_TIMESTAMP
)
ON CONFLICT ("key") DO UPDATE SET
    "provider" = EXCLUDED."provider",
    "providerModelId" = EXCLUDED."providerModelId",
    "type" = EXCLUDED."type",
    "displayName" = EXCLUDED."displayName",
    "qualityTier" = EXCLUDED."qualityTier",
    "supportedAspectRatios" = EXCLUDED."supportedAspectRatios",
    "supportedResolutions" = EXCLUDED."supportedResolutions",
    "supportsStartFrame" = EXCLUDED."supportsStartFrame",
    "supportsEndFrame" = EXCLUDED."supportsEndFrame",
    "supportsSeed" = EXCLUDED."supportsSeed",
    "active" = EXCLUDED."active",
    "updatedAt" = CURRENT_TIMESTAMP;
