ALTER TABLE "AiModel"
ADD COLUMN IF NOT EXISTS "usageRequestCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "usagePromptTokensUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "usageCompletionTokensUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "usageReasoningTokensUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "usageTotalTokensUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "usageGeneratedImages" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "lastUsedAt" TIMESTAMP(3);

INSERT INTO "AiModel" (
    "id",
    "key",
    "provider",
    "providerModelId",
    "type",
    "displayName",
    "qualityTier",
    "supportedAspectRatios",
    "supportedResolutions",
    "supportsStartFrame",
    "supportsEndFrame",
    "supportsSeed",
    "pricePerSecondByResolution",
    "minDurationSeconds",
    "maxDurationSeconds",
    "defaultDurationSeconds",
    "active",
    "updatedAt"
) VALUES (
    'aimodel_gemini_3_1_flash_image',
    'gemini-3-1-flash-image',
    'fal',
    'fal-ai/nano-banana-2',
    'text-to-image',
    'Gemini 3.1 Flash Image',
    'fast',
    ARRAY['auto', '21:9', '16:9', '3:2', '4:3', '5:4', '1:1', '4:5', '3:4', '2:3', '9:16', '4:1', '1:4', '8:1', '1:8'],
    ARRAY['0.5K', '1K', '2K', '4K'],
    false,
    false,
    true,
    '{}'::jsonb,
    1,
    1,
    1,
    true,
    CURRENT_TIMESTAMP
)
ON CONFLICT ("key") DO UPDATE SET
    "provider" = EXCLUDED."provider",
    "providerModelId" = EXCLUDED."providerModelId",
    "type" = EXCLUDED."type",
    "displayName" = EXCLUDED."displayName",
    "qualityTier" = EXCLUDED."qualityTier",
    "supportedAspectRatios" = EXCLUDED."supportedAspectRatios",
    "supportedResolutions" = EXCLUDED."supportedResolutions",
    "supportsStartFrame" = EXCLUDED."supportsStartFrame",
    "supportsEndFrame" = EXCLUDED."supportsEndFrame",
    "supportsSeed" = EXCLUDED."supportsSeed",
    "active" = EXCLUDED."active",
    "updatedAt" = CURRENT_TIMESTAMP;
