INSERT INTO "AiModel" (
    "id",
    "key",
    "provider",
    "providerModelId",
    "type",
    "displayName",
    "qualityTier",
    "supportedAspectRatios",
    "supportedResolutions",
    "supportsStartFrame",
    "supportsEndFrame",
    "supportsSeed",
    "pricePerSecondByResolution",
    "minDurationSeconds",
    "maxDurationSeconds",
    "defaultDurationSeconds",
    "active",
    "updatedAt"
) VALUES (
    'aimodel_gpt_image_2',
    'gpt-image-2',
    'fal',
    'openai/gpt-image-2',
    'text-to-image',
    'GPT Image 2',
    'premium',
    ARRAY[]::TEXT[],
    ARRAY[]::TEXT[],
    false,
    false,
    false,
    '{}'::jsonb,
    1,
    1,
    1,
    true,
    CURRENT_TIMESTAMP
)
ON CONFLICT ("key") DO UPDATE SET
    "provider" = EXCLUDED."provider",
    "providerModelId" = EXCLUDED."providerModelId",
    "type" = EXCLUDED."type",
    "displayName" = EXCLUDED."displayName",
    "qualityTier" = EXCLUDED."qualityTier",
    "supportedAspectRatios" = EXCLUDED."supportedAspectRatios",
    "supportedResolutions" = EXCLUDED."supportedResolutions",
    "supportsStartFrame" = EXCLUDED."supportsStartFrame",
    "supportsEndFrame" = EXCLUDED."supportsEndFrame",
    "supportsSeed" = EXCLUDED."supportsSeed",
    "active" = EXCLUDED."active",
    "updatedAt" = CURRENT_TIMESTAMP;
