INSERT INTO "AiModel" (
    "id",
    "key",
    "provider",
    "providerModelId",
    "type",
    "displayName",
    "qualityTier",
    "supportedAspectRatios",
    "supportedResolutions",
    "supportsStartFrame",
    "supportsEndFrame",
    "supportsSeed",
    "pricePerSecondByResolution",
    "minDurationSeconds",
    "maxDurationSeconds",
    "defaultDurationSeconds",
    "active",
    "updatedAt"
) VALUES (
    'aimodel_gemini_3_pro_image',
    'gemini-3-pro-image',
    'fal',
    'fal-ai/nano-banana-pro',
    'text-to-image',
    'Gemini 3 Pro Image',
    'premium',
    ARRAY['auto', '21:9', '16:9', '3:2', '4:3', '5:4', '1:1', '4:5', '3:4', '2:3', '9:16'],
    ARRAY['1K', '2K', '4K'],
    false,
    false,
    true,
    '{}'::jsonb,
    1,
    1,
    1,
    true,
    CURRENT_TIMESTAMP
)
ON CONFLICT ("key") DO UPDATE SET
    "provider" = EXCLUDED."provider",
    "providerModelId" = EXCLUDED."providerModelId",
    "type" = EXCLUDED."type",
    "displayName" = EXCLUDED."displayName",
    "qualityTier" = EXCLUDED."qualityTier",
    "supportedAspectRatios" = EXCLUDED."supportedAspectRatios",
    "supportedResolutions" = EXCLUDED."supportedResolutions",
    "supportsStartFrame" = EXCLUDED."supportsStartFrame",
    "supportsEndFrame" = EXCLUDED."supportsEndFrame",
    "supportsSeed" = EXCLUDED."supportsSeed",
    "active" = EXCLUDED."active",
    "updatedAt" = CURRENT_TIMESTAMP;
